FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/

COPY index.html /usr/share/nginx/html/

COPY pageA.html /usr/share/nginx/html/
COPY pageB.html /usr/share/nginx/html/
COPY sendGetPost.js /usr/share/nginx/html/

